
img_w: 256
img_h: 256

img_crop_w: 224
img_crop_h: 224

batch_size: 16
epochs: 10
save_every_epoch: 2
val_every_epoch: 1

sent_neutral_absval: 0.5
min_bc_class_size: -1



basic_cnn:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.01
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.01
    bc:
        optim: adam
        lr: 0.01

vgg:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.01
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.01
    bc:
        optim: adam
        lr: 0.01

vgg_finetune:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.01
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.01
    bc:
        optim: adam
        lr: 0.01