
img_w: 256
img_h: 256

img_crop_w: 224
img_crop_h: 224

batch_size: 16
epochs: 20
dropout: 0.5
weight_decay_lreg: 0.0005
bn_decay: 0.9
save_every_epoch: 1
val_every_epoch: 1

sent_neutral_absval: 0.5
min_bc_class_size: -1



basic_cnn:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.01
        ckpt_dir: 2016-12-26___02-09-30
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.005
    bc:
        optim: adam
        lr: 0.01

basic_plus_cnn:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.01
        ckpt_dir: 2016-12-26___02-09-30
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.005
    bc:
        optim: adam
        lr: 0.01

alexnet:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.01
        ckpt_dir: 2016-12-26___02-09-30
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.005
    bc:
        optim: sgd
        lr: 0.01

vgg:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.005
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.01
    bc:
        optim: adam
        lr: 0.01

vgg_finetune:
    sent_reg:
        optim: adam
        lr: 0.01
    sent_biclass:
        optim: adam
        lr: 0.01
    sent_triclass:
        optim: adam
        lr: 0.01
    emo:
        optim: adam
        lr: 0.01
    bc:
        optim: adam
        lr: 0.01